=== icanseetime/Assignment-5/a5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <!-- Root: Cookbook -->
    <xs:element name="cookbook">
        <xs:complexType>
            <xs:sequence>
                <!-- Cake -->
                <xs:element name="cake" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>

                            <!-- Name -->
                            <xs:element name="name" type="xs:string" />

                            <!-- Serves -->
                            <xs:element name="serves">
                                <xs:simpleType>
                                    <xs:restriction base="xs:int">
                                        <xs:minInclusive value="2" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Cooking time -->
                            <xs:element name="time">
                                <xs:simpleType>
                                    <xs:restriction base="xs:duration">
                                        <xs:maxInclusive value="PT300M" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Cooking temperature -->
                            <xs:element name="temperature">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="([0-9])*\s(°F|°C)" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Oven type -->
                            <xs:element name="ovenType">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Gas" />
                                        <xs:enumeration value="Fan" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Difficulty -->
                            <xs:element name="difficulty">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Easy" />
                                        <xs:enumeration value="Medium" />
                                        <xs:enumeration value="Professional" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>

                            <!-- Special remarks -->
                            <xs:element name="specialRemarks" type="xs:string" minOccurs="0" />

                            <!-- Recipe -->
                            <xs:element name="recipe">
                                <xs:complexType>
                                    <xs:sequence>
                                        <!-- Ingredient -->
                                        <xs:element name="ingredient" minOccurs="2" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <!-- Type of ingredient -->
                                                    <xs:element name="type" type="xs:string" />
                                                    <!-- Quantity -->
                                                    <xs:element name="quantity">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="amount" type="xs:decimal" />
                                                                <xs:element name="measuringType" type="xs:string" />
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>
</xs:schema>

=== icanseetime/Assignment-5/a5.xml
<?xml version="1.0" encoding="UTF-8"?>
<cookbook xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="a5.xsd">
    <cake>
        <name>Pavlova</name>
        <serves>8</serves>
        <time unit="minutes">90</time>
        <temperature type="fahrenheit">200</temperature>
        <oven-type>Fan</oven-type>
        <difficulty>Medium</difficulty>
        <special-remarks>Gluten-free</special-remarks>
        <recipe>
            <ingredient>
                <type>Egg whites</type>
                <quantity type="pieces">4</quantity>
            </ingredient>
            <ingredient>
                <type>Superfine sugar</type>
                <quantity type="grams">200</quantity>
            </ingredient>
            <ingredient>
                <type>Vanilla extract</type>
                <quantity type="teaspoons">1</quantity>
            </ingredient>
            <ingredient>
                <type>Cornstarch</type>
                <quantity type="teaspoons">1</quantity>
            </ingredient>
            <ingredient>
                <type>White vinegar</type>
                <quantity type="tablespoons">2</quantity>
            </ingredient>
        </recipe>
    </cake>
    <cake>
        <name>Carrot cake</name>
        <serves>10</serves>
        <time unit="minutes">30</time>
        <temperature type="celsius">160</temperature>
        <oven-type>Gas</oven-type>
        <difficulty>Easy</difficulty>
        <recipe>
            <ingredient>
                <type>All-purpose flour</type>
                <quantity type="grams">250</quantity>
            </ingredient>
            <ingredient>
                <type>Baking soda</type>
                <quantity type="teaspoons">2</quantity>
            </ingredient>
            <ingredient>
                <type>Cinnamon</type>
                <quantity type="teaspoons">1</quantity>
            </ingredient>
            <ingredient>
                <type>Sunflower oil</type>
                <quantity type="ml">290</quantity>
            </ingredient>
            <ingredient>
                <type>Superfine salt</type>
                <quantity type="teaspoons">0.5</quantity>
                <!-- TODO: specify that decimals are allowed?  -->
            </ingredient>
            <ingredient>
                <type>Sugar</type>
                <quantity type="grams">200</quantity>
            </ingredient>
            <ingredient>
                <type>Vanilla extract</type>
                <quantity type="teaspoons">1</quantity>
            </ingredient>
            <ingredient>
                <type>Grated carrots</type>
                <quantity type="cups">3</quantity>
            </ingredient>
            <ingredient>
                <type>Eggs</type>
                <quantity type="pieces">4</quantity>
            </ingredient>
        </recipe>
    </cake>
</cookbook>
